# Creates a new preview deployment on Vercel's platform, when anything is pushed in any branch (except for the "master" branch).
name: Deploy to Vercel (staging)

on:
  push:
    branches-ignore:
      - "master"

    paths:
      - ".github/workflows/deploy-vercel-staging.yml"
      - "public/**"
      - "src/**"
      - ".eslint*"
      - "*.js*"
      - "*.ts"
      - ".*ignore"
      - "yarn.lock"
      - "!**/*.md"
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup deployment environment (Ubuntu 18.04 - Node 14.x)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
